### ISSUE TITLE
Invidious doesn't appear to work?

### ISSUE THREAD

**Issue by SheepCommander** [TaiAurori/embed-redirect#4]
Just gives me black screen

![image](https://user-images.githubusercontent.com/66646514/148755697-604a0271-8e58-4e06-8248-01ac6c7b3494.png)
![image](https://user-images.githubusercontent.com/66646514/148755702-bd4ebad4-0372-4580-b00a-a311eb08ec98.png)

**Comment by TaiAurori** [comment]
Are you using the default instance, or a custom one?

**Comment by SheepCommander** [comment]
Powercord and plugin are unmodified

**Comment by TaiAurori** [comment]
Try a few other Invidious instances from [here](https://github.com/iv-org/documentation/blob/master/Invidious-Instances.md), might be a CORS issue.

**Comment by SheepCommander** [comment]
Ah, got yewtu.be to work thx
